# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Scalesage Dev"
client_id = "b276cf7766baf62c68a3d536f2e3431b"
application_url = "https://fake-shopify-dev-app.local/sign-in"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,read_products"

[auth]
redirect_urls = [ "https://fake-shopify-dev-app.local/api/oauth/shopify/callback" ]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/webhooks/shopify/orders-create"

[build]
include_config_on_deploy = true
